apiVersion: v1
kind: ReplicationController
metadata:
  name: data-cassandra-v000
  namespace: spinnaker
  labels:
    app: data
    stack: cassandra
    version: v000
spec:
  replicas: 1
  selector:
    replication-controller: data-cassandra-v000
  template:
    metadata:
      labels:
        replication-controller: data-cassandra-v000
        load-balancer-data-cassandra: "true"
    spec:
      containers:
        - command:
            - /run.sh
          resources:
            limits:
              cpu: 0.1
          env:
            - name: MAX_HEAP_SIZE
              value: 512M
            - name: HEAP_NEWSIZE
              value: 100M
            - name: POD_NAMESPACE
              value: "spinnaker"
            - name: CASSANDRA_SERVICE
              value: "data-cassandra"
          image: gcr.io/google-samples/cassandra:v8
          name: cassandra
          ports:
            - containerPort: 9042
              name: cql
            - containerPort: 9160
              name: thrift
          volumeMounts:
            - mountPath: /cassandra_data
              name: data
      volumes:
        - name: data
          emptyDir: {}
