apiVersion: v1
kind: ReplicationController
metadata:
  name: spkr-front50-v000
  namespace: spinnaker
  labels:
    app: spkr
    stack: front50
    version: v000
spec:
  replicas: 1
  selector:
    replication-controller: spkr-front50-v000
  template:
    metadata:
      labels:
        replication-controller: spkr-front50-v000
        load-balancer-spkr-front50: "true"
    spec:
      containers:
        - image: quay.io/spinnaker/front50:latest
          name: front50
          ports:
            - containerPort: 8080
              name: front50
          volumeMounts:
            - mountPath: /opt/spinnaker/config
              name: spinnaker-config
          readinessProbe:
            httpGet:
              path: /env
              port: 8080
            initialDelaySeconds: 20
            timeoutSeconds: 1
      volumes:
        - name: spinnaker-config
          secret:
            secretName: spinnaker-config
