apiVersion: v1
kind: ReplicationController
metadata:
  name: spkr-deck-v000
  namespace: spinnaker
  labels:
    app: spkr
    stack: deck
    version: v000
spec:
  replicas: 1
  selector:
    replication-controller: spkr-deck-v000
  template:
    metadata:
      labels:
        replication-controller: spkr-deck-v000
        load-balancer-spkr-deck: "true"
    spec:
      containers:
        - image: quay.io/spinnaker/deck:latest
          name: deck
          command:
            - /bin/bash
            - -c
          args:
            - "cp /opt/spinnaker/config/settings.js .; npm start"
          ports:
            - containerPort: 9000
              name: deck
          volumeMounts:
            - mountPath: /opt/spinnaker/config
              name: spinnaker-config
      volumes:
        - name: spinnaker-config
          secret:
            secretName: spinnaker-config
