apiVersion: v1
kind: ReplicationController
metadata:
  name: spkr-orca-v000
  namespace: spinnaker
  labels:
    app: spkr
    stack: orca
    version: v000
spec:
  replicas: 1
  selector:
    replication-controller: spkr-orca-v000
  template:
    metadata:
      labels:
        replication-controller: spkr-orca-v000
        load-balancer-spkr-orca: "true"
    spec:
      containers:
        - image: quay.io/spinnaker/orca:latest
          name: orca
          ports:
            - containerPort: 8083
              name: orca
          volumeMounts:
            - mountPath: /opt/spinnaker/config
              name: spinnaker-config
          readinessProbe:
            httpGet:
              path: /env
              port: 8083
            initialDelaySeconds: 20
            timeoutSeconds: 1
      volumes:
        - name: spinnaker-config
          secret:
            secretName: spinnaker-config
