server:
    port: ${services.rush.port:8085}
    address: 0.0.0.0

cassandra:
  embedded: ${services.cassandra.embedded:false}
  host: ${services.cassandra.host:localhost}

spinnaker:
  cassandra:
    cluster: ${services.cassandra.cluster:spinnaker}
    keyspace: 'rush'

docker:
  accounts:
    - name: ${services.docker.primaryAccount.name}
      url: ${services.docker.primaryAccount.url}
      registry: ${services.docker.primaryAccount.registry}
