server:
  port: ${services.front50.port:8080}
  address: ${services.front50.host:localhost}

cassandra:
  enabled: ${services.cassandra.enabled:true}
  embedded: ${services.cassandra.embedded:false}
  host: ${services.cassandra.host:localhost}

aws:
  simpleDBEnabled: ${providers.aws.simpleDBEnabled:false}
  defaultSimpleDBDomain: ${providers.aws.defaultSimpleDBDomain}

spinnaker:
  cassandra:
    enabled: true
    host: ${services.cassandra.host:localhost}
    port: ${services.cassandra.port:9042}
    cluster: ${services.cassandra.cluster:CASS_SPINNAKER}
    keyspace: front50
    name: global
