x509:
  enabled: true
  subjectPrincipalRegex: CN=(.*?)
#  subjectPrincipalRegex: EMAILADDRESS=(.*?)(?:,|$) # optional

server:
  ssl:
    clientAuth: want
    #enabledProtocols: "TLSv1,TLSv1.1,TLSv1.2"
    enabled: true
    keyStore: /opt/spinnaker/ssl/keystore.jks
    #keyStore: /opt/spinnaker/ssl/keystore.jks
    keyStorePassword: {{ SPINNAKER_KEYSTORE_PASS }}
    keyAlias: server
    trustStore: /opt/spinnaker/ssl/keystore.jks
    #trustStore: /opt/spinnaker/ssl/keystore.jks
    trustStorePassword: {{ SPINNAKER_KEYSTORE_PASS }}

    #keyStore: /opt/spinnaker/config/keystore.jks
    #keyStorePassword: poop12345
    #keyAlias: server
    #trustStore: /opt/spinnaker/config/keystore.jks
    #trustStorePassword: poop12345
