x509:
  enabled: true
  subjectPrincipalRegex: CN=(.*?)

server:
  ssl:
    clientAuth: want
    enabled: true
    keyStore: /opt/spinnaker/ssl/keystore.jks
    keyStorePassword:
    keyAlias: server
    trustStore: /opt/spinnaker/ssl/keystore.jks
    trustStorePassword:
