spring:
  oauth2:
    client:
      clientId: 138980857772-as4k6qo834on7esbjgmd4s6m9i797bu5.apps.googleusercontent.com
      clientSecret: xfH2qPaHtpXcc97-sX4YhpQb
      #userAuthorizationUri: https://accounts.google.com/o/oauth2/v2/auth?access_type=offline&hd=stitchfix.com
