server:
  port: ${services.igor.port:8088}
  address: ${services.igor.host:localhost}

jenkins:
  masters:
    - name: ${services.jenkins.defaultMaster.name}
      address: ${services.jenkins.defaultMaster.baseUrl}
      username: ${services.jenkins.defaultMaster.username}
      password: ${services.jenkins.defaultMaster.password}

redis:
  connection: ${services.redis.connection:redis://localhost:6379}

# This is recursive
#services:
#  echo:
#    baseUrl: ${services.echo.baseUrl}
