server:
    port: ${services.rush.port:8085}
    address: ${services.rush.host:localhost}

rush:
  polling:
    orphanedExecutionTimeoutMinutes: 30
    runningExecutionUpdateIntervalSeconds: 15
    canceledExecutionUpdateIntervalSeconds: 30
  jobs:
    local:
      timeoutMinutes: 10

cassandra:
  embedded: ${services.cassandra.embedded:false}
  host: ${services.cassandra.host:localhost}

spinnaker:
  cassandra:
    cluster: ${services.cassandra.cluster:spinnaker}
    keyspace: 'rush'

docker:
  accounts:
    - name: ${services.docker.primaryAccount.name}
      url: ${services.docker.primaryAccount.url}
      registry: ${services.docker.primaryAccount.registry}
