apiVersion: v1
kind: Service
metadata:
  name: data-cassandra
  namespace: spinnaker
  labels:
    app: data
    stack: cassandra
spec:
  ports:
    - port: 9042
      name: cql
    - port: 9160
      name: thrift
  selector:
    load-balancer-data-cassandra: "true"
