apiVersion: v1
kind: Service
metadata:
  name: spkr-gate
  namespace: spinnaker
  labels:
    app: spkr
    stack: gate
spec:
  ports:
    - port: 8084
  selector:
    load-balancer-spkr-gate: "true"
