apiVersion: v1
kind: Service
metadata:
  name: spkr-front50
  namespace: spinnaker
  labels:
    app: spkr
    stack: front50
spec:
  ports:
    - port: 8080
  selector:
    load-balancer-spkr-front50: "true"
