apiVersion: v1
kind: Service
metadata:
  name: spkr-echo
  namespace: spinnaker
  labels:
    app: spkr
    stack: echo
spec:
  ports:
    - port: 8089
  selector:
    load-balancer-spkr-echo: "true"
