apiVersion: v1
kind: Service
metadata:
  name: spkr-igor
  namespace: spinnaker
  labels:
    app: spkr
    stack: igor
spec:
  ports:
    - port: 8088
  selector:
    load-balancer-spkr-igor: "true"
