apiVersion: v1
kind: Service
metadata:
  name: spkr-orca
  namespace: spinnaker
  labels:
    app: spkr
    stack: orca
spec:
  ports:
    - port: 8083
  selector:
    load-balancer-spkr-orca: "true"
