apiVersion: v1
kind: Service
metadata:
  name: spkr-clouddriver
  namespace: spinnaker
  labels:
    app: spkr
    stack: clouddriver
spec:
  ports:
    - port: 7002
  selector:
    load-balancer-spkr-clouddriver: "true"
