apiVersion: v1
kind: Service
metadata:
  name: spkr-deck
  namespace: spinnaker
  labels:
    app: spkr
    stack: deck
spec:
  ports:
    - port: 9000
  selector:
    load-balancer-spkr-deck: "true"
