apiVersion: extensions/v1beta1
kind: Job
metadata:
  name: data-cassandra-keys
  namespace: spinnaker
  labels:
    app: data
    stack: cassandra
    details: keys
spec:
  template:
    metadata:
      labels:
        job-controller: data-cassandra-keys 
    spec:
      containers:
      - name: cassandra-keys
        image: gcr.io/kubernetes-spinnaker/cassandra-keys:v2
      restartPolicy: Never
